import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Conway’s Game of Life",
  description:
    "Dive into the mesmerizing world of Conway's Game of Life! Experience the magic of simple rules " +
    "creating captivating patterns in this classic cellular automaton simulation. " +
    "Explore the beauty of algorithmic evolution and enjoy the ever-changing landscapes generated by the game. " +
    "Discover the simplicity behind the complexity of Life itself.",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
